language: java
jdk:
- openjdk11
env:
  global:
  - VERSION=$(git rev-parse --short HEAD)
  - GITHUB_APP_ID=21626
  - DOCKER_USERNAME=naviktdocker
  - secure: DRjIjrWi55zc0mykrIVadUYVBR94M5ozsDj/FhnDp7uF4SmYH+naA1JiL1wzPEJWxHYcX2prQEEvOauKcZZxBttIlZ4egZP+6gazae6cAdVbvEph9ti/ZAJCm6XxDHPK/bZhNHvqU82yyAFRBXgoIVp4UxNg3BVCA7UJZ2MuiO9XindSzR1BPHMbf+ygDmT6lZv1APz0dWCBTl3l0x6aY5IqME010NOnAP5oHfbHusaYD1AIu35YZ6B0M19Mo3hvtsyG/ix8o+FRUSJO8BtDHgE32vzXQXdx5CnnmmgSGM/xPlyfhP1rWQbU/UXNTVUI/0tkHEvVKzmLGuvnRBkMFGqR1jc7819glkpFGtl23G0Aj2/XddXgZUc32yfBU1BtU9bftaQ+758GRY8iY6eDrPthyg1FQcL3ewl9E4wuOfeiSVv4k0babJAgmMrGxmGdpzJvn/DUlDwWqIUXkueHY8ZhKAf8mojmnCI6Y9hSHfspEd3B9k2qmJKmrUISF+jRVNH88AWMeR9jhh8ayRHMzaQO54/uAOYQGoy4Owps3doZcKxDEaFWBLrdRq52cy0IdRsuxr0zZECJWmblwcR5gE2DanfFP95OLOKR8n21QvRb0DDbv70a86MY40jRh5ITFh1YocE7wtHGPDbYtnIhY6MktuEBjA9icF1XU1hx3CA=
before_install:
- openssl aes-256-cbc -K $encrypted_8baa07224b9d_key -iv $encrypted_8baa07224b9d_iv
  -in travis/team-dagpenger.private-key.pem.enc -out travis/team-dagpenger.private-key.pem -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/team-dagpenger.private-key.pem
  $GITHUB_APP_ID`)
stages:
- Tests
- Deploy
jobs:
  include:
  - stage: Tests
    script: "./gradlew check --info"
  - stage: Deploy
    if: branch = master
    script: skip
    deploy:
      provider: script
      script: travis/deploy.sh
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
notifications:
  slack:
    rooms:
      secure: KuTM77V+5dJdVqH4Gks6cAekw75pGv9bLgokNY+h3yHmeRVfz9rZb/jZJykO4Txzy20UaBRisXjfjv6zxNt/MNRCLdZaBNUHMjvdyucI7AWTKCXd71OqvOuOybR6MeyHSxyyOjuKZClXIqmAnvPwLQ1iAc3zmjYQMaylKeIqVxRfl9C1Bl2R+vGf+nGMKyGy8tydjuqhibeHIV43synJqcFIGV3+WEUYFMKtKv+mRmDjdzDejxeeLqoKFdE1ZlKJZHLHe7SUDe/aBBAmoAoAWROarclbpnDC+mvqIIDCQRO5PuZcxNzEk67AyXmwG81vS6nrRmWIqzE3tOiCsBCsZt9Jy3ndrewVecltIIUYTtcisgs7CtM6Wo99WYI0+V2iRJLsLrcmBIdx3FF4aTgc7vOw/7IN3D4oZ4zfpsWERaMIcpUmJuUZZ83urwGV5lqOe3HXeZsnMzmLLoSwwk6zAwxxL0Flf2Dbl25aY3YEkrosGgPdSSueoftOl8ZUExNGGJ4tR1S75lRClXCDA3SYILTfC2khc6CQtFuMia7X4oh1UfS9g9is3eSqGqRpmh+oKtKoSg9I+I3q2NrD12Z39RVj+KP08UDW5KmKkD2YSMz2hAfZvaUSDnypr7Yxi/SvU0xZkI9S88R6LEfKDAOOjGtvUI9uYG37ACPDU5WFbEg=
  on_pull_requests: false
