language: java
jdk:
- openjdk11
env:
  global:
  - VERSION=$(git rev-parse --short HEAD)
  - GITHUB_APP_ID=21626
  - DOCKER_IMG_NAME=naviktdocker/dagpenger-journalforing-gsak
  - DOCKER_USERNAME=naviktdocker
  - secure: ARkjBhFwqDqAp48vWMzDTGhTStMS8EUxbgV6tIduwrS0Iy1sgHemFD2sooJwRHdagi6dKmPzZTP2+5Rvyy2FqjS6l1kCF+aXKfOEZDFGC5PZPDGs5kasl7yEy77Wdndc9K5Oby/Pkd7VsuiIGr/MR4orAdEgSNO3HMz7lpXDMFcNb7OI+PTYvclGQI9X+xdFZP7Qr6WAuJJRtRlRA9tSN87GE89r+U7F7N1sEnbFCH4d62H0cGt6XET7caest79tzqZ8iNS2Is62nRNOfyb5Iic2wNFLKoMq4gz6iIJmqKu9F6RpSPl90XSeV+Krfo/5Ord+1BiT9MezFLC2GYznpSQfpDo7nHJ5fTxx//h89WygPRP9W5vIT5Rnt2kV4X6oiXXHIt9Mr4HaNwEfO6yA458T7PwJvnz+Rv0COuxyMNP1ts+swjYiI7ouU+h5CPEL6L6R0zXtfCvy0+dMoz2T+7l70PCbVqQGfs/XKFGaMWpOX9FvcutaXCgflEhstYe+mk3D1jU9yrWkYGS/40GB5GLbifUnDs5fQbGrc/QlW/yqEaexrDcyw1F2Ax0wu28qrCwc4MQ9RcPPKhIWPFs8J8+wnNOK6IEGgx3PPAQp11v3xXzOnBz6L+b8qPag2jtNplGc5iVZk6Hd816mEe9DfQp6CmwNNFzwOxDPYnxvACk=
before_install:
- openssl aes-256-cbc -K $encrypted_8baa07224b9d_key -iv $encrypted_8baa07224b9d_iv
  -in travis/team-dagpenger.private-key.pem.enc -out travis/team-dagpenger.private-key.pem
  -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/team-dagpenger.private-key.pem $GITHUB_APP_ID`)
stages:
- Tests
- Deploy
jobs:
  include:
  - stage: Tests
    script: "./gradlew check"
  - stage: Deploy
    if: branch = master
    script: "./gradlew clean build -x check"
    deploy:
      skip_cleanup: true
      provider: script
      script: travis/deploy.sh
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
notifications:
  slack:
    rooms:
      secure: KuTM77V+5dJdVqH4Gks6cAekw75pGv9bLgokNY+h3yHmeRVfz9rZb/jZJykO4Txzy20UaBRisXjfjv6zxNt/MNRCLdZaBNUHMjvdyucI7AWTKCXd71OqvOuOybR6MeyHSxyyOjuKZClXIqmAnvPwLQ1iAc3zmjYQMaylKeIqVxRfl9C1Bl2R+vGf+nGMKyGy8tydjuqhibeHIV43synJqcFIGV3+WEUYFMKtKv+mRmDjdzDejxeeLqoKFdE1ZlKJZHLHe7SUDe/aBBAmoAoAWROarclbpnDC+mvqIIDCQRO5PuZcxNzEk67AyXmwG81vS6nrRmWIqzE3tOiCsBCsZt9Jy3ndrewVecltIIUYTtcisgs7CtM6Wo99WYI0+V2iRJLsLrcmBIdx3FF4aTgc7vOw/7IN3D4oZ4zfpsWERaMIcpUmJuUZZ83urwGV5lqOe3HXeZsnMzmLLoSwwk6zAwxxL0Flf2Dbl25aY3YEkrosGgPdSSueoftOl8ZUExNGGJ4tR1S75lRClXCDA3SYILTfC2khc6CQtFuMia7X4oh1UfS9g9is3eSqGqRpmh+oKtKoSg9I+I3q2NrD12Z39RVj+KP08UDW5KmKkD2YSMz2hAfZvaUSDnypr7Yxi/SvU0xZkI9S88R6LEfKDAOOjGtvUI9uYG37ACPDU5WFbEg=
    on_pull_requests: false
    on_success: never # default: change
    on_failure: always # default: always
