# Example https://github.com/nais/naiserator/blob/master/examples/nais-max.yaml
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dagpenger-journalforing-gsak
  namespace: default
  labels:
    team: teamdagpenger
  annotations:
    zone: fss
spec:
  image: repo.adeo.no:5443/dagpenger-journalforing-gsak:latest
  port: 8080
  team: teamdagpenger
  liveness:
    path: isAlive
  readiness:
    path: isReady
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 1000m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
  env:
    - name: DAGPENGER_OPPSLAG_API_URL
      value: http://dagpenger-oppslag/
    - name: OIDC_STS_ISSUERURL
      value: https://security-token-service/ # http://security-token-service
