# Example https://github.com/nais/naiserator/blob/master/examples/app.yaml
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dagpenger-journalforing-gsak
  labels:
    team: teamdagpenger
spec:
  image: naviktdocker/dagpenger-journalforing-gsak:latest
  port: 8080
  liveness:
    path: isAlive
  readiness:
    path: isReady
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 1000m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /metrics
  env:
    - name: DAGPENGER_OPPSLAG_API_URL
      value: http://dagpenger-oppslag
    - name: OIDC_STS_ISSUERURL
      value: https://security-token-service-q1.nais.preprod.local # http://security-token-service